#!/usr/bin/env python3
"""Generate the Pydantic v2 document models from ``schema/``.

`engine/cf-schema` is the single source of truth for the data contract (ADR 0001).
The JSON Schema in ``schema/`` is generated from it, and *these* Pydantic models are
generated from that JSON Schema. Nothing in ``importer/schema/`` is ever hand-written —
if a document type is wrong, fix the Rust and regenerate both.

Run via ``make models`` from ``services/``, or directly::

    python scripts/gen_models.py

Writes ``importer/schema/{venue,scenario}.py`` plus its ``__init__.py``. That directory
contains *only* generated files, deliberately: a directory has one owner.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

SERVICES = Path(__file__).resolve().parent.parent
REPO = SERVICES.parent
SCHEMA_DIR = REPO / "schema"
OUT_DIR = SERVICES / "importer" / "schema"

#: ``(json schema file, generated module, root pydantic class)``.
DOCUMENTS = [
    ("venue.schema.json", "venue.py", "VenueDoc"),
    ("scenario.schema.json", "scenario.py", "ScenarioDoc"),
]

BANNER = """\
# GENERATED from schema/{source} — do not edit.
# Regenerate with: make models   (from services/)
# The source of truth is engine/cf-schema (ADR 0001).
"""

INIT = '''\
# GENERATED by scripts/gen_models.py — do not edit.
# Regenerate with: make models   (from services/)
"""Pydantic v2 models for the CrowdFlow document types.

Generated from ``schema/*.json``, which is itself generated from ``engine/cf-schema``.
"""

from importer.schema.scenario import ScenarioDoc
from importer.schema.venue import VenueDoc

__all__ = ["ScenarioDoc", "VenueDoc"]
'''


def generate() -> int:
    """Regenerate every model module. Returns a process exit code."""
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for source, module, root in DOCUMENTS:
        src = SCHEMA_DIR / source
        if not src.is_file():
            print(f"missing {src} — run `cargo run -p cf-schema --bin gen-schema`", file=sys.stderr)
            return 1
        dst = OUT_DIR / module
        cmd = [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            str(src),
            "--input-file-type",
            "jsonschema",
            "--output",
            str(dst),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--target-python-version",
            "3.12",
            "--class-name",
            root,
            "--use-double-quotes",
            "--use-annotated",
            "--use-standard-collections",
            "--use-union-operator",
            "--use-schema-description",
            "--use-field-description",
            "--enum-field-as-literal",
            "all",
            "--collapse-root-models",
            "--disable-timestamp",
            "--custom-file-header",
            BANNER.format(source=source).rstrip("\n"),
        ]
        print("  ".join(["gen", source, "->", str(dst.relative_to(SERVICES))]))
        result = subprocess.run(cmd, check=False)
        if result.returncode != 0:
            return result.returncode

    (OUT_DIR / "__init__.py").write_text(INIT, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(generate())
