# GENERATED by scripts/gen_models.py — do not edit.
# Regenerate with: make models   (from services/)
"""Pydantic v2 models for the CrowdFlow document types.

Generated from ``schema/*.json``, which is itself generated from ``engine/cf-schema``.
"""

from importer.schema.scenario import ScenarioDoc
from importer.schema.venue import VenueDoc

__all__ = ["ScenarioDoc", "VenueDoc"]
